include:
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/golang/stages/10-code-check/go.yaml'
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/golang/stages/20-security/go.yaml'
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/golang/stages/30-tests/go.yaml'
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/golang/stages/40-delivery/goreleaser.yaml'
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/golang/stages/50-deployment/debrelease.yaml'

stages:
  - 'code check (style/quality)'
  - 'security (sca/sast)'
  - 'tests'
  - 'delivery'
  - 'deployment'
