include:
  - local: '/global/abstracts/default-image.yaml'
  - local: '/logstash/stages/20-security/logstash.yaml'
  - local: '/logstash/stages/35-management/logstash.yaml'
  - local: '/global/stages/40-delivery/docker.yaml'

stages:
  - 'security (sca/sast)'
  - 'management'
  - 'delivery'
