include:
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/java/abstracts/gradle-application.yaml'
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/java/stages/10-code-check/gradle.yaml'

.code-check:
  extends: '.gradle-application'
