#  coverage: '/total.*?([0-9]{1,3}[.][0-9]{0,2})%/'
#  artifacts:
#    when: 'always'
#    paths:
#      - 'coverage.*'
#    reports:
#      coverage_report:
#        coverage_format: 'cobertura'
#        path: 'coverage.xml'

stages:
  - stage: 'tests'
    displayName: 'tests'
    jobs:
      - job: 'test_all'
        displayName: 'test:all'
        steps:
          - task: 'GoTool@0'
            inputs:
              version: '1.20'
          # TODO: this should be a share script between the vendors
          - script: '[[ -f config.sh ]] && ./config.sh'
          - script: touch coverage.xml
          - script: |
              go test -v -tags test,unit,integration
                -coverpkg ./main/...
                -covermode=count ./main/...
                -coverprofile=coverage.txt
          - script: go tool cover -func coverage.txt
          - script: go install github.com/boumenot/gocover-cobertura@latest
          - script: gocover-cobertura < coverage.txt > coverage.xml
