stages:
  - stage: 'security'
    displayName: 'security (sca/sast)'
    jobs:
      - template: '../../../global/stages/20-security/docker.yaml'
        parameters:
          semgrepLang: 'golang'
      # TODO: another Go security job
